version: "3.8"

services:
  frontend:
    image: v1
    build:
      context: ./client
      dockerfile: dockerfile
    container_name: frontend
    ports:
      - "80:3000"
  backend:
          image: v2
          build:
            context: ./backend
            dockerfile: dockerfile
          container_name: backend
          ports:
            - "8080:3001"